# Generated by Django 4.1.3 on 2022-11-16 21:17

import apps.schedule.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_course'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('break_after', models.PositiveSmallIntegerField()),
                ('start_at', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_days', to='lessons.lesson')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.schedule')),
            ],
            options={
                'unique_together': {('ordering', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEST', 'Test'), ('COMPENDIUM', 'Compendium'), ('TASK', 'Task')], max_length=32)),
                ('file', models.FileField(upload_to=apps.schedule.models._get_upload_to)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='schedule.schedulelesson')),
            ],
        ),
    ]
